apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  type: NodePort
  selector:
    app: springboot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30007  # Change if using a different NodePort
