apiVersion: v1
kind: Secret
metadata:
  name: springboot-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVhPUUZENVNFV09ZNloyUDI=
  AWS_SECRET_ACCESS_KEY: cmJTaHdKcDN6aDI3UnY4Mnc2QzNDZ08veTRBUDlqYm9ucm54eUlTNw==
