apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  aws-access-key-id: QUtJQVhPUUZENVNFU09OR0NLVjY=
  aws-secret-access-key: S2ZiV2VGSHRwWWhYM25JMHI5V0xnR2ZSUEsvZkQzRmhVYTh0SHZOUw==