name: CI/CD Pipeline

on:
  push:
    branches:
      - dikshita

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'  

    - name: Build with Maven
      run: mvn clean package -Dmaven.test.skip=true

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER_D }}
        password: ${{ secrets.DOCKER_HUB_PASS_D }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: disidesh/spring-boot:latest
        build-args: PROFILE=your-profile