name: CI Pipeline for Image Uploader

on:
  push:
    branches:
      - my-ci-branch
  pull_request:
    branches:
      - my-ci-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'  # You can change this to 'zulu' or any other distribution you prefer
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD_M }}" | docker login -u "${{ secrets.DOCKER_USERNAME_M }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t maansireddy15/imageuploaderapp .

    - name: Push Docker Image
      run: docker push maansireddy15/imageuploaderapp
