name: CI Pipeline for Image Uploader

on:
  push:
    branches:
      - my-ci-branch
  pull_request:
    branches:
      - my-ci-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t maansireddy15/imageuploaderapp .

    - name: Push Docker Image
      run: docker push maansireddy15/imageuploaderapp
