name: Deploy to Kubernetes

on:
  push:
    branches:
      - features/dikshita
  pull_request:
    branches:
      - features/dikshita

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'  

    - name: Build with Maven
      run: mvn clean package -Dmaven.test.skip=true

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER_D }}
        password: ${{ secrets.DOCKER_HUB_PASS_D }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: disidesh/spring-boot:latest
        build-args: PROFILE=your-profile

  deploy_to_kubernetes:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Install DOCTL command
      run: |
        sudo snap install doctl
        sudo snap connect doctl:kube-config

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Digital Ocean Credentials
      run: |
        doctl auth init --access-token ${{ secrets.DO_ACCOUNT_TOKEN }}
        doctl kubernetes cluster kubeconfig save do-nyc3-cerebrone-dev  # Use your actual cluster name here

    - name: Deploy Helm on DOKS
      run: |
        helm upgrade --install spring-boot-application spring-boot-app-chart/ \
          -f spring-boot-app-chart/templates/values.yaml \
          --set image.tag=${{ github.sha }} \
          --namespace ${{ vars.K8S_NAMESPACE }}  # Use the variable here