# .github/workflows/deploy.yml
name: Deploy to Kubernetes

on:
  push:
    branches:
      - features/dikshita # Change to your branch name as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Test with Maven
        run: mvn test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER_D }} # Ensure this secret exists in GitHub Secrets.
          password: ${{ secrets.DOCKER_HUB_PASS_D }} # Ensure this secret exists in GitHub Secrets.

      - name: Build Docker Image
        run: docker build -t disidesh/spring-boot .

      - name: Push Docker Image to Docker Hub
        run: docker push disidesh/spring-boot

      - name: Set up Kubeconfig for Kubernetes access
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config # Ensure this secret exists.

      #- name: Install Helm (if not already installed)
      #  run: |
       #   curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3.sh | bash

      #- name: Deploy to Kubernetes with Helm using NodePort service type 
       # run: |
       #   helm upgrade --install spring-boot-app ./spring-boot-app-chart \
       #     --set image.tag=latest \
       #     --namespace your-namespace --create-namespace 