name: Deploy to Kubernetes

on:
  push:
    branches:
      - features/shaik
  pull_request:
    branches:
      - features/shaik

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package -Dmaven.test.skip=true

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_ACCOUNT_TOKEN }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME_D }}
        password: ${{ secrets.DOCKER_TOKEN_D }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: shaik2024/my-app:latest
        build-args: PROFILE=your-profile

  deploy_to_kubernetes:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Install DOCTL command
      run: |
        sudo snap install doctl
        sudo snap connect doctl:kube-config

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Digital Ocean Credentials
      run: |
        doctl auth init --access-token ${{ secrets.DO_ACCOUNT_TOKEN }}
        doctl kubernetes cluster kubeconfig save 37a5f702-e1a8-4732-9490-f5e047b5a724  # Replace with your cluster ID

    - name: Set AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_D }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_D }}" >> $GITHUB_ENV

    - name: Deploy Helm on DOKS
      run: |
        helm upgrade --install spring-boot-application spring-boot-app-chart \
          -f spring-boot-app-chart/values.yaml \
          --set image.tag=latest \
          --namespace interns  # Replace with your actual namespace