name: remote ssh command

on:
  push:
    branches:
      - shaik  # Only run on the 'shaik' branch
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami