name: remote ssh command

on:
  push:
    branches:
      - shaik  # Only run on the 'shaik' branch
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  build:
    name: remote ssh 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > training-key.pem
        chmod 600 training-key.pem

    - name: Execute remote SSH commands
      run: |
        ssh -i training-key.pem root@ec2-54-82-146-94.compute-1.amazonaws.com << 'EOF'
          whoami
          sudo apt-get update -y
          sudo apt-get upgrade -y
        EOF