name: Remote SSH Command

on:
  push:
    branches:
      - shaik
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Execute remote SSH commands
    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}               # The public DNS or IP of the EC2 instance
        username: ${{ secrets.USERNAME }}       # The SSH username for the EC2 instance
        key: ${{ secrets.SSH_PRIVATE_KEY }}     # The private SSH key for authentication
        port: ${{ secrets.PORT }}                # The SSH port (default is 22)
        script: |
          echo "Executing commands on remote server..."
          whoami                                  # Print the current user
          ls -al                                   # List files in the current directory
          docker --version                         # Check the Docker version