name: Deploy to EC2

on:
  push:
    branches:
      - shaik # Trigger this action on push to the main branch
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create SSH Key File
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2-key.pem
        chmod 400 ec2-key.pem  # Set correct permissions for the private key

    - name: Connect to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}           # EC2 public IP or DNS (set as secret in GitHub)
        username: ${{ secrets.EC2_USER }}       # EC2 username (e.g., ec2-user or ubuntu, set as secret)
        key: ec2-key.pem                        # Path to the private key file with correct permissions
        port: 22                                # SSH port (usually 22)
        script: |
          echo "Successfully logged into EC2"
          # Further commands here, e.g., check Minikube status, etc.
          uname -a
