apiVersion: apps/v1
kind: Deployment
metadata:
  name: shaik-k8s
  labels:
    app: spring-boot-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always 
          ports:
            - containerPort: {{ .Values.service.port }}  # Ensure this matches your application port
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secret-aws  # Ensure this matches the name of your Kubernetes secret
                  key: AWS_ACCESS_KEY_ID_S # This should match the key in your secret
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-aws
                  key: AWS_SECRET_ACCESS_KEY_S # This should match the key in your secret